### ISSUE TITLE
Add frame-src (to provide support for UAs that don't yet support child-src)

### ISSUE THREAD

**Issue by muffinresearch** [yahoo/express-csp#11]
For example child-src is only supported in firefox 45 onwards. [1] . I'm not sure about other browsers aside from Chrome which has supported it from version 40.

[1] https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Browser_compatibility

**Comment by dtomack** [comment]
It would be nice if this was supported.  Is this project still being actively supported?

**Comment by muffinresearch** [comment]
See also more recent spec which un-deprecates frame-src: https://w3c.github.io/webappsec-csp/#changes-from-level-2
