### ISSUE TITLE
extendPolicy

### ISSUE THREAD

**Issue by jasonmit** [yahoo/express-csp#9]
`res.setPolicy` will overwrite the global csp config.  The proposal is to add `res.extendPolicy` will do a shallow merge with the global.

**Comment by caridy** [comment]
we talked about this a while ago, and it seems to me that the result of this operation is gonna be tricky, especially if you want to overrule something that was defined in a previous extendPolicy call. How to merge those two structures? In general, I think the computation of the config is a business logic that can be carry on by the app, and this pkg should just consume the config.
